# Generated by Django 4.0.5 on 2022-06-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='icon',
        ),
    ]
