# Generated by Django 4.0.5 on 2022-06-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_task_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
