# Generated by Django 4.0.5 on 2022-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_task_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='itext',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
