# Generated by Django 4.0.5 on 2022-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_task_itext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='itext',
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.URLField(max_length=600),
        ),
    ]
